### PR TITLE
Code Fix

### LINKED ISSUE #114: f863316031b8f973ab09e98dea420991c48d3af67d42545ad961b98908c9e111
f863316031b8f973ab09e98dea420991c48d3af67d42545ad961b98908c9e111

_Originally posted by @4911775157 in https://github.com/safemoonprotocol/Safemoon.sol/pull/93#discussion_r815242088_

### LINKED ISSUE #119: https://github.com/4911775157
Safemoon.sol

safemoon contract Safemoon protocol is a mixture of RFI tokenomics with the added function of auto-liquidity generating protocol. A fork from BEE with some added benefits. First, the dev has minted the tokens - sent the balance to DxSale for fair launch - and then burned the remainder of the tokens. Dev had to partake in presale. Second, utilized the DxSale protocol to foster trust in the community by auto-locking liquidity for 4 years. Simple tokenomics and elegant design and production of token information has catered to the overall success of the project. 100% community owned and driven - no rug is possible. #safemoon join us on our journey safely to the moon

https://github.com/4911775157
https://t.me/Alieghbali65
0x7aC0295f78b8868a36Ed233B2e838d191bF567cf

### PR DESCRIPTION
**Pull request by Slitherings**

### CODE REVIEW

**Comment by Slitherings** [comment]
Let me do a favor for all these people getting scammed.

**Comment by tygas** [comment]
@Slitherings define scam. People earned huge amounts of money on the coin. Couple whales dumped their bags and price went down. Smartcontract working perfectly and taking fees it should.

So where is the problem?

**Comment by andreapigatto** [comment]
> Let me do a favor for all these people getting scammed.

At least you know that smart contracts are not editable and you need to write a new one to change it

**Review by ghost — APPROVED** [review]

**Comment by Slitherings** [comment]
> @Slitherings define scam. People earned huge amounts of money on the coin. Couple whales dumped their bags and price went down. Smartcontract working perfectly and taking fees it should.
> 
> So where is the problem?

Where is the problem? The entire github repository is the problem.. If you can type on youtube "Blockchain Development Tutorial"  You will get almost a complete Replica of this Solidity file, the problem with this repository is that none of the sub-directories exist, this will bottleneck the development period. I don't know if he made a choice to include the babel files and other components in the .gitignore but the chances of people being able to make pull request and make additional features for the repository are slim to none, unless someone out there wants to add another thousand lines of code into this one solidity file... I don't care about people making a "profit" because this project doesn't look like it will have a long life span because it will be just a catalyst for pump and dumps, to make people FOMO into it...

**Comment by Slitherings** [comment]
https://www.youtube.com/watch?v=99pYGpTWcXM Here you go

**Comment by andreapigatto** [comment]
Clearly this file was just posted to "have a look at the core code".. is clearly not intended for collaboration.. project is not in development but already live.. how you want to collaborate on a smart contract already deployed in blockchain that is immutable? :)

**Comment by sambeaCA** [comment]
> Clearly this file was just posted to "have a look at the core code".. is clearly not intended for collaboration.. project is not in development but already live.. how you want to collaborate on a smart contract already deployed in blockchain that is immutable? :)

"One way to update the code is to create an intermediary Smart Contract that will hold the address of the active Smart Contract. So all the calls and transactions will be redirected to the active version with the function **delegatecall**. That way, you’ll be using the same contract address but that contract will execute a different Smart Contract code in the end. From an “updated” contract."

Another way is to simply extract all the information from the old contract and insert it into a new version. Then update the address that your users will see.

**Comment by andreapigatto** [comment]
> > Clearly this file was just posted to "have a look at the core code".. is clearly not intended for collaboration.. project is not in development but already live.. how you want to collaborate on a smart contract already deployed in blockchain that is immutable? :)
> 
> 
> 
> "One way to update the code is to create an intermediary Smart Contract that will hold the address of the active Smart Contract. So all the calls and transactions will be redirected to the active version with the function **delegatecall**. That way, you’ll be using the same contract address but that contract will execute a different Smart Contract code in the end. From an “updated” contract."
> 
> 
> 
> Another way is to simply extract all the information from the old contract and insert it into a new version. Then update the address that your users will see.

Thanks nice to know ;) smart contracts are always described as immutable plus really prone to errors, bugs etc. Solidity is not that easy and stable language

**Comment by tre-dev** [comment]
The creators didn't write 99.99% of the code themselves. They copy-pasted & changed some variables. They have a single contract within this repo, instead of different folders i.e. for unit tests etc., because they're lazy marketers and probably used a web editor to copy/paste the contract.

The fact that nobody seems to care enough for this to have billions in market cap is sickening, especially considering that people WILL get burned and many will be left as bag-holders. When this happens, cryptocurrencies as a whole will be blamed. Great way to invite regulations by the way.

FYI: this is a how a repository is supposed to look like when developers actually write code themselves and maintain the smart contract(s):

https://github.com/axieinfinity/ronin-smart-contracts

**Comment by andreapigatto** [comment]
> The creators didn't write 99.99% of the code themselves. They copy-pasted & changed some variables. They have a single contract within this repo, instead of different folders i.e. for unit tests etc., because they're lazy marketers and probably used a web editor to copy/paste the contract.
> 
> 
> 
> The fact that nobody seems to care enough for this to have billions in market cap is sickening, especially considering that people WILL get burned and many will be left as bag-holders. When this happens, cryptocurrencies as a whole will be blamed. Great way to invite regulations by the way.
> 
> 
> 
> FYI: this is a how a repository is supposed to look like when developers actually write code themselves and maintain the smart contract(s):
> 
> 
> 
> https://github.com/axieinfinity/ronin-smart-contracts

I think main problem here is that everybody think this is an open source project just cause been shared in GitHub. It looks clearly a read only file just to show it to the community/for documentation (you find link on official website).. I don't think is intended for collaboration. Safemoon protocol and this smart contract is live and that's it. If there will be changes they will be made by the internal team. At same time doesn't look there is a real skilled tech team behind for now. Maybe question is if this is like a random file or is legit and do exactly what safemoon protocol should do. Looking a bit fast to it seems like a legit implementation of it.

**Comment by tre-dev** [comment]
> It looks clearly a read only file just to show it to the community/for documentation (you find link on official website).. I don't think is intended for collaboration. 

There is nothing else. They copied an existing contract, changed some variables and published the code to Github as well.

Contract: https://bscscan.com/address/0x8076c74c5e3f5852037f31ff0093eeb8c8add8d3#code
Similar Contracts: https://tokensniffer.com/token/0x8076c74c5e3f5852037f31ff0093eeb8c8add8d3

**Comment by Denimbeard** [comment]
They have been open from the start that it is a modified Bee token, so I don't see what the problem is.

**Comment by ScottyXIII** [comment]
hahahaha. Beautiful - PR approved! Get rid of this shitcoin scam please.

**Review by ScottyXIII — APPROVED** [review]
LGTM!

**Comment by ghost** [comment]
25800

در تاریخ دوشنبه ۲۶ آوریل ۲۰۲۱،‏ ۰:۵۸ Scott ***@***.***> نوشت:

**Comment by sambeaCA** [comment]
Are they even monitoring the fact that were chatting within the PR?

**Comment by Slitherings** [comment]
> Are they even monitoring the fact that were chatting within the PR?

No they don't care, their spreading fake information by having some random dude in a suit talk about "partnering with Africa"?? and other random topics, this is just one big scam and its sad because I'm seeing hundreds of thousands of people supporting them in the comment section... It's already started, hundreds of thousands will lose money because of this project....

**Comment by Slitherings** [comment]
https://twitter.com/papacthulu < This is the guy who prob copy pasta the code, lawsuits will be hitting this guy.

**Comment by ScottyXIII** [comment]
I'm not a smart contract dev so I may be misunderstanding something in the code here but both the owner and smart contract are excluded from their fees? I can understand the smart contract but why also the owner? 
is the owner the smart contract in this context or the dev that deployed the smart contract? is this normal to do something like this? 

https://github.com/safemoonprotocol/Safemoon.sol/blob/main/Safemoon.sol#L1049 

Both the owner and smart contract are exempt from the fees here: 
https://github.com/safemoonprotocol/Safemoon.sol/blob/main/Safemoon.sol#L767

**Comment by tre-dev** [comment]
> https://twitter.com/papacthulu < This is the guy who prob copy pasta the code, lawsuits will be hitting this guy.

He read through every single line of code though!

https://www.twitch.tv/videos/995850298?t=00h50m00s

**Comment by tre-dev** [comment]
> is the owner the smart contract in this context or the dev that deployed the smart contract? is this normal to do something like this?

owner is the address that deployed the smart contract. Though it's a valid question why that one is exempt from fees as well. Maybe it's easier to dump tokens without being hit with 10% fees. ;)

**Comment by ScottyXIII** [comment]
> > https://twitter.com/papacthulu < This is the guy who prob copy pasta the code, lawsuits will be hitting this guy.
> 
> He read through every single line of code though!
> 
> https://www.twitch.tv/videos/995850298?t=00h50m00s

Dam he even tells people not to just copy paste code and to understand it. Irony!!!
These guys are such clowns, I mean they're not even monitoring this code repo lol.

**Comment by andreapigatto** [comment]
> > > https://twitter.com/papacthulu < This is the guy who prob copy pasta the code, lawsuits will be hitting this guy.
> 
> > 
> 
> > He read through every single line of code though!
> 
> > 
> 
> > https://www.twitch.tv/videos/995850298?t=00h50m00s
> 
> 
> 
> Dam he even tells people not to just copy paste code and to understand it. Irony!!!
> 
> These guys are such clowns, I mean they're not even monitoring this code repo lol.  

Man the project is called safemoon no safecode 😂😂 when u will be there you can forget about GitHub and this code

**Comment by PiecePaperCode** [comment]
could it be that there could be a function that swaps all the tokens from SM to ETH? Can we veryfy this source code with the actual binary code thats is deployed as the smart contract?

**Comment by ScottyXIII** [comment]
> could it be that there could be a function that swaps all the tokens from SM to ETH? Can we veryfy this source code with the actual binary code thats is deployed as the smart contract?

I believe you can see the live contract here => https://bscscan.com/address/0x8076c74c5e3f5852037f31ff0093eeb8c8add8d3#code

It's shows you the solidity code and you can see the params with their values and also query some stuff.

**Review by justinemar — APPROVED** [review]

**Comment by ScottyXIII** [comment]
Honestly can we talk about the fact the devs can change the fees and have access to set any address to be exempt from the fees lol? 
am I completely misunderstanding how this contract works here or just losing my mind? 

Owner can add addresses to the excluded from fees array - I believe this can also be changes after the contract has been deployed?  It's a public onlyOwner function.
https://github.com/safemoonprotocol/Safemoon.sol/blob/main/Safemoon.sol#L891
You can even query the live contract to find the address are exempt. 

and here the owner can change the fee amount after the contract has been deployed: 
https://github.com/safemoonprotocol/Safemoon.sol/blob/main/Safemoon.sol#L899

**Comment by PiecePaperCode** [comment]
i see that the owner can change the tax fee. what if they change it to 100%. this coin becomes worthless.

**Comment by Jovonni** [comment]
good dialogue.

They added a new repo with the contract under their GitHub organization, so post your questions there.

I just added this issue to inquire about where the burn and reflection logic actually resides.

https://github.com/Safemoon-Protocol/safemoon.sol/issues/1

**Review by PiecePaperCode — APPROVED** [review]

**Comment by PiecePaperCode** [comment]
> good dialogue.
> 
> They added a new repo with the contract under their GitHub organization, so post your questions there.
> 
> I just added this issue to inquire about where the burn and reflection logic actually resides.
> 
> [Safemoon-Protocol/safemoon.sol#1](https://github.com/Safemoon-Protocol/safemoon.sol/issues/1)

# To Anser your questions in my best knowledge as i understand this codebase
**10% Tax**
Here The Owner has exkluded himself
https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L1114
Everybody else pays the tax
https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L1134

**5% gets added to the LP** 
https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L964
the contract adress gets the LP Fee `_rOwned[address(this)] = _rOwned[address(this)].add(rLiquidity);`

**5% Token gets Burned**
https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L921
the burned amount just gets added to an variable and are taken away from the total supply variable
as per this code there is **no** **Burned Wallet** you just get returned an int of the total burned amount.

**Whats the 0 Adress? With no surprice the owner of the contract himself.**
https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L481

# and here is how the owner will rugpull out
**set Tax to 100%, 0% 50%**
He can make prevent people of pulling out of this contract
https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L899
Think about if Satoshi could just 100% the fees all by himself BTC would be worthless

### This Code was copypasted and a couple of lines are changed. So there is some dead code in ther that dosent run or is runned by another contract but i dont know ether.

**Comment by blendicavlad** [comment]
> > good dialogue.
> > They added a new repo with the contract under their GitHub organization, so post your questions there.
> > I just added this issue to inquire about where the burn and reflection logic actually resides.
> > [Safemoon-Protocol/safemoon.sol#1](https://github.com/Safemoon-Protocol/safemoon.sol/issues/1)
> 
> # To Anser your questions in my best knowledge as i understand this codebase
> **10% Tax**
> Here The Owner has exkluded himself
> https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L1114
> Everybody else pays the tax
> https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L1134
> 
> **5% gets added to the LP**
> https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L964
> the contract adress gets the LP Fee `_rOwned[address(this)] = _rOwned[address(this)].add(rLiquidity);`
> 
> **5% Token gets Burned**
> https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L921
> the burned amount just gets added to an variable and are taken away from the total supply variable
> as per this code there is **no** **Burned Wallet** you just get returned an int of the total burned amount.
> 
> **Whats the 0 Adress? With no surprice the owner of the contract himself.**
> https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L481
> 
> # and here is how the owner will rugpull out
> **set Tax to 100%, 0% 50%**
> He can make prevent people of pulling out of this contract
> https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L899
> Think about if Satoshi could just 100% the fees all by himself BTC would be worthless
> 
> ### This Code was copypasted and a couple of lines are changed. So there is some dead code in ther that dosent run or is runned by another contract but i dont know ether.



> > good dialogue.
> > They added a new repo with the contract under their GitHub organization, so post your questions there.
> > I just added this issue to inquire about where the burn and reflection logic actually resides.
> > [Safemoon-Protocol/safemoon.sol#1](https://github.com/Safemoon-Protocol/safemoon.sol/issues/1)
> 
> # To Anser your questions in my best knowledge as i understand this codebase
> **10% Tax**
> Here The Owner has exkluded himself
> https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L1114
> Everybody else pays the tax
> https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L1134
> 
> **5% gets added to the LP**
> https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L964
> the contract adress gets the LP Fee `_rOwned[address(this)] = _rOwned[address(this)].add(rLiquidity);`
> 
> **5% Token gets Burned**
> https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L921
> the burned amount just gets added to an variable and are taken away from the total supply variable
> as per this code there is **no** **Burned Wallet** you just get returned an int of the total burned amount.
> 
> **Whats the 0 Adress? With no surprice the owner of the contract himself.**
> https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L481
> 
> # and here is how the owner will rugpull out
> **set Tax to 100%, 0% 50%**
> He can make prevent people of pulling out of this contract
> https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L899
> Think about if Satoshi could just 100% the fees all by himself BTC would be worthless
> 
> ### This Code was copypasted and a couple of lines are changed. So there is some dead code in ther that dosent run or is runned by another contract but i dont know ether.

You can read CertiK security audit, they and the SafeMoon team explain your concerns https://www.certik.org/projects/safemoon

**Comment by alisolanki** [comment]
> > > good dialogue.
> > > They added a new repo with the contract under their GitHub organization, so post your questions there.
> > > I just added this issue to inquire about where the burn and reflection logic actually resides.
> > > [Safemoon-Protocol/safemoon.sol#1](https://github.com/Safemoon-Protocol/safemoon.sol/issues/1)
> > 
> > 
> > # To Anser your questions in my best knowledge as i understand this codebase
> > **10% Tax**
> > Here The Owner has exkluded himself
> > https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L1114
> > Everybody else pays the tax
> > https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L1134
> > **5% gets added to the LP**
> > https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L964
> > the contract adress gets the LP Fee `_rOwned[address(this)] = _rOwned[address(this)].add(rLiquidity);`
> > **5% Token gets Burned**
> > https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L921
> > the burned amount just gets added to an variable and are taken away from the total supply variable
> > as per this code there is **no** **Burned Wallet** you just get returned an int of the total burned amount.
> > **Whats the 0 Adress? With no surprice the owner of the contract himself.**
> > https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L481
> > # and here is how the owner will rugpull out
> > **set Tax to 100%, 0% 50%**
> > He can make prevent people of pulling out of this contract
> > https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L899
> > Think about if Satoshi could just 100% the fees all by himself BTC would be worthless
> > ### This Code was copypasted and a couple of lines are changed. So there is some dead code in ther that dosent run or is runned by another contract but i dont know ether.
> 
> > > good dialogue.
> > > They added a new repo with the contract under their GitHub organization, so post your questions there.
> > > I just added this issue to inquire about where the burn and reflection logic actually resides.
> > > [Safemoon-Protocol/safemoon.sol#1](https://github.com/Safemoon-Protocol/safemoon.sol/issues/1)
> > 
> > 
> > # To Anser your questions in my best knowledge as i understand this codebase
> > **10% Tax**
> > Here The Owner has exkluded himself
> > https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L1114
> > Everybody else pays the tax
> > https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L1134
> > **5% gets added to the LP**
> > https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L964
> > the contract adress gets the LP Fee `_rOwned[address(this)] = _rOwned[address(this)].add(rLiquidity);`
> > **5% Token gets Burned**
> > https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L921
> > the burned amount just gets added to an variable and are taken away from the total supply variable
> > as per this code there is **no** **Burned Wallet** you just get returned an int of the total burned amount.
> > **Whats the 0 Adress? With no surprice the owner of the contract himself.**
> > https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L481
> > # and here is how the owner will rugpull out
> > **set Tax to 100%, 0% 50%**
> > He can make prevent people of pulling out of this contract
> > https://github.com/Safemoon-Protocol/safemoon.sol/blob/0f0aef2f4e6ca00d6a46ca6ea60caa4d36c5fd6f/Safemoon.sol#L899
> > Think about if Satoshi could just 100% the fees all by himself BTC would be worthless
> > ### This Code was copypasted and a couple of lines are changed. So there is some dead code in ther that dosent run or is runned by another contract but i dont know ether.
> 
> You can read CertiK security audit, they and the SafeMoon team explain your concerns https://www.certik.org/projects/safemoon

Can you tell me exactly where they have mentioned the issue of a possible rug pull if the tax is changed to 100% and why owner is excluded from fees? In the audit they haven't even listed that as an issue let alone give a solution for it.

**Comment by PiecePaperCode** [comment]
@alisolanki 

> Can you tell me exactly where they have mentioned the issue of a possible rug pull 
<h4>Here</h4>

image

**they clearly mention this issue as priviliged ownership in the audit.** 



> if the tax is changed to 100% 
<h4>its one of the possibility to rug pull not even the only one. Maby they dont want people to cash out.</h4>



> and why owner is excluded from fees? 
<h4>depending on the use case this can be a good thing. But it can do harm as well. If he is cashing out he wont pay reflections.
and he can grant it to other wallets as well. like promoters who will dump it risk free if the time is right</h4>



> In the audit they haven't even listed that as an issue let alone give a solution for it.
<h4>yes they have and its clearly listed as an issue. if the owners key gets compromised or stolen. all funds are lost or at high risk. an compromised owner of the safemoon contract will result in massive loses of value and trust. there is no benefit in investing in a crypto that is that centralized. rather bring it to the bank where at least the state guarantees a minimum for it.

**Comment by ScottyXIII** [comment]
> You can read CertiK security audit, they and the SafeMoon team explain your concerns https://www.certik.org/projects/safemoon


Why do people bang on about the CertiK review so much? We can all read the terrible review which states the EXACT same problems we're talking about here and the SM team have never addressed the issues beyond 'Just trust us'.  So how exactly does this explain our concerns? 

I also find it rather ironic that a coin called 'Safe'Moon shows the lowest score in their safety assessment.... What the actual F?! 

My best guess was this coin was initially set up to either be a scam or an extremely low effort cash grab and people started throwing their money at it. Any one who can read code can see this is nothing more than trash copy and paste. Hell you don't even need to be able to read code to see the references to other coins in the comments at the start of the contract!!

**Comment by PiecePaperCode** [comment]
It happend. 100% tax on the contract. 🥳🥳🥳

**Comment by ScottyXIII** [comment]
Lol. Good job this is a decentralised technology and not one person or entity has contr....... OH, 100% tax ;) 

Now I wonder what sorta control they have over the new contract lol......

**Comment by Tr0ublesh00ter** [comment]
The thing that cracked me up is that some bozo wrote on twitter that Safemoon is not just a cryptocurrency, they are a tech company (lool).
 Then some other dumbass wrote in comments that Safemoon has better technology then Polygon and that was the second most liked comment hhahahahah.
But on a serious note, this project is going to be horrible advertisment for cryptocurrency space as a whole. already is, but when they pull a fast one its gonna be much worse.

**Comment by PiecePaperCode** [comment]
i couldnt find V2 Source Code. The project beceme less trustworthy. 

this is the the reason i started mining me some Skepticoin.

Nobody Cares about the thechnology/developers as long it makes money. Thats sad!!!

**Comment by ScottyXIII** [comment]
> @Slitherings define scam. People earned huge amounts of money on the coin. Couple whales dumped their bags and price went down. Smartcontract working perfectly and taking fees it should.
> 
> So where is the problem?

Do you see the problem now lol or you still blind as a bat? Even with full access to read the source code some of you couldn't or wouldn't see what this was.

**Pull request closed without merging**
